version: '3'

services:
  db:
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
    - MYSQL_USER=ragzinho
    - MYSQL_PASSWORD=ragzinho
    - MYSQL_DATABASE=ragzinho
    - MYSQL_ROOT_PASSWORD=ragzinho
    volumes:
    - "ragzinho_mysql:/home/ubuntu/ragzinho/db_ragzinho"

volumes:
  ragzinho_mysql: { driver: local }
